#!/bin/bash

sudo update-alternatives --set gcc /usr/bin/gcc-8
sudo update-alternatives --set g++ /usr/bin/g++-8
sudo update-alternatives --set cpp /usr/bin/cpp-8

echo ""
gcc --version | grep gcc
g++ --version | grep g++
cpp --version | grep cpp
echo ""

if ! command -v rustup >/dev/null 2>&1; then
  echo "Error: rustup is not installed. Please install before running this script."
  echo ""
  echo "To install rust if needed:"
  echo "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  echo ""
  exit 1
fi

CHECK_OUTPUT=$(rustup check)

get_version() {
    local search_term="$1"
    local line=$(echo "$CHECK_OUTPUT" | grep "$search_term")

    [ -z "$line" ] && return

    if echo "$line" | grep -q "update available"; then
        # Case: 1.96.1 (...) -> 1.97.0 (...)
        echo "$line" | awk -F ' -> ' '{print $2}' | awk '{print $1}'
    elif echo "$line" | grep -q "up to date"; then
        # Case: up to date : 1.97.0 (...)
        echo "$line" | awk -F ':' '{print $NF}' | awk '{print $1}'
    fi
}

RUSTC_VER_AVAIL=$(get_version "stable-x86_64")
RUSTUP_VER_AVAIL=$(get_version "rustup")

RUSTC_VER_CURRENT=$(rustc --version | awk '{print $2}')
RUSTUP_VER_CURRENT=$(rustup --version 2>&1 | awk '/^rustup/ {print $2}')

if [ -z "$RUSTC_VER_AVAIL" ] && [ -z "$RUSTUP_VER_AVAIL" ]; then
    echo "Could not check for updates"
    echo ""
    exit 1
fi

if [ "$RUSTC_VER_AVAIL" != "$RUSTC_VER_CURRENT" ] || [ "$RUSTUP_VER_AVAIL" != "$RUSTUP_VER_CURRENT" ]; then
    echo "Rust updates available"
    echo ""
    echo "rustc:  $RUSTC_VER_CURRENT -> $RUSTC_VER_AVAIL"
    echo "rustup: $RUSTUP_VER_CURRENT -> $RUSTUP_VER_AVAIL"
    echo ""
    read -p "Would you like to update now? [y/N] " response
    case "$response" in
        [yY]*)
            echo "Updating rust"
            echo ""
            rustup update
            ;;
        *)
            echo "Skipping update"
            echo ""
            ;;
    esac
else
    echo "rustup/rustc are up to date"
    echo ""
fi

export PKG_CONFIG_PATH="$(pwd)/build_libs/lib/pkgconfig"

export OPENSSL_DIR="$(pwd)/build_libs"
export OPENSSL_LIB_DIR="$(pwd)/build_libs/lib"
export OPENSSL_INCLUDE_DIR="$(pwd)/build_libs/include"

export SQLITE3_DIR="$(pwd)/build_libs"
export SQLITE3_LIB_DIR="$(pwd)/build_libs/lib"
export SQLITE3_INCLUDE_DIR="$(pwd)/build_libs/include"

echo "Building static libraries"
echo ""

make -f build-libs

echo ""
echo "Building static Arti debian package"
echo ""

cd arti
./build-debian.sh
