#!/bin/bash

sudo update-alternatives --set gcc /usr/bin/gcc-8
sudo update-alternatives --set g++ /usr/bin/g++-8
sudo update-alternatives --set cpp /usr/bin/cpp-8

gcc --version
g++ --version
cpp --version

if ! command -v rustup >/dev/null 2>&1; then
  echo "Error: rustup is not installed. Please install before running this script."
  echo ""
  echo "To install rust if needed:"
  echo "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  exit 1
fi

CHECK_OUTPUT=$(rustup check)
RUSTC_VER_AVAIL=$(echo "$CHECK_OUTPUT" | grep "stable-x86_64" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
RUSTUP_VER_AVAIL=$(echo "$CHECK_OUTPUT" | grep "rustup" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')

RUSTC_VER_CURRENT=$(rustc --version | awk '{print $2}')
RUSTUP_VER_CURRENT=$(rustup --version 2>&1 | awk '/^rustup/ {print $2}')

if [ -z "$RUSTC_VER_AVAIL" ]; then
    echo "Could not check for updates"
    exit 1
fi

if [ "$RUSTC_VER_AVAIL" != "$RUSTC_VER_CURRENT" ] || [ "$RUSTUP_VER_AVAIL" != "$RUSTUP_VER_CURRENT" ]; then
    echo "Rust updates available"
    echo ""
    echo "rustc:  $RUSTC_VER_CURRENT -> $RUSTC_VER_AVAIL"
    echo "rustup: $RUSTUP_VER_CURRENT -> $RUSTUP_VER_AVAIL"

    read -p "Would you like to update now? [y/N] " response
    case "$response" in
        [yY]*)
            echo "Updating rust"
            echo ""
            rustup update
            ;;
        *)
            echo "Skipping update"
            echo ""
            ;;
    esac
else
    echo "rustup/rustc are up to date"
    echo ""
fi

if ! rustup target list | grep -q "aarch64-linux-android (installed)"; then
    echo "Adding android native arm64 target for rust"
    rustup target add aarch64-linux-android
else
    echo "Android arm64 target is already installed"
fi

echo ""
echo "Installing/updating cargo-ndk"
cargo install cargo-ndk

export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865
export ANDROID_NDK_ROOT=$ANDROID_NDK_HOME

export PKG_CONFIG_PATH="$(pwd)/build_libs/lib/pkgconfig"

export OPENSSL_DIR="$(pwd)/build_libs"
export OPENSSL_LIB_DIR="$(pwd)/build_libs/lib"
export OPENSSL_INCLUDE_DIR="$(pwd)/build_libs/include"

export SQLITE3_DIR="$(pwd)/build_libs"
export SQLITE3_LIB_DIR="$(pwd)/build_libs/lib"
export SQLITE3_INCLUDE_DIR="$(pwd)/build_libs/include"

sudo update-alternatives --set python3 /usr/bin/python3.14
python3 --version

#python3 -m pip download ninja
#python3 -m pip download cmake

python3 -m pip install --user tools/ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl
python3 -m pip install --user tools/cmake-3.26.4-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl

make -f build-tools
make -f build-libs-arm64

python3 -m pip uninstall -y ninja
python3 -m pip uninstall -y cmake

sudo update-alternatives --auto python3

cd arti

cargo ndk --platform 24 --target aarch64-linux-android build --release --locked -p arti --features=static,full
